### 13장 텐서플로를 사용하여 신경망 훈련
- 1) 텐서플로 기초 조작
--- 

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings(action='ignore')

In [3]:
#!pip install tensorflow
import tensorflow as tf

---
#### 1. tensor 조작 기초 
- tf.conver_to_tensor : 리스트, 넘파이 배열로 부터 텐서 만들기 
- tf.ones(), tf.zeros(), tf.one_hot(), tf.fill(), tf.cast(), tf.reshape(), tf.squeeze(), tf.expand_dims()
---

In [11]:
## 넘파이 array -> tensor 
a = [1,2,3]
b = [4,5,6]
print(a, b)

t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)
print(t_a, t_b)

[1, 2, 3] [4, 5, 6]
tf.Tensor([1 2 3], shape=(3,), dtype=int32) tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [23]:
## tf.ones(), tf.zeros() : 0 또는 1로 구성된 텐서 만들기 
## tensor의 참조값을 얻으려면 .numpy() 사용
c = tf.ones([2,3])
d = tf.zeros([4,5])
print(c, '\n' ,d)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32) 
 tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(4, 5), dtype=float32)


In [24]:
## tf.one_hot(i, j) : 원-핫 인코딩에 유용, i는 원핫코딩 위치 인덱스 - j는 원핫코딩 인코딩 벡터 길이  
tf.one_hot([0,1,2],4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [27]:
## tf.fill(i, j) : 원하는 스칼라 값으로 채워진 텐서 만들기. i는 텐서의 크기를, j는 채우려는 스칼라 값 
tf.fill((2,3), 9)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

In [85]:
## tf.constant() : 특정값으로 텐서 만들기 
tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2, 2, 3])

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [37]:
## tf.cast() : 텐서의 타입 변경 
print(t_a.dtype)
t_a_new1 = tf.cast(t_a, tf.int64)
t_a_new2 = tf.cast(t_a, tf.float32)
print(t_a_new1.dtype)
print(t_a_new2.dtype)

<dtype: 'int32'>
<dtype: 'int64'>
<dtype: 'float32'>


In [40]:
## tf.transfose : 텐서의 전치 (ex. 3x5 --> 5x3)
t = tf.random.uniform(shape = (3,5))
print(t)

t_tr = tf.transpose(t)
print(t_tr)

tf.Tensor(
[[0.39882398 0.9811106  0.9230019  0.77371573 0.2190746 ]
 [0.5428877  0.9329668  0.11001396 0.7496586  0.7730926 ]
 [0.86151195 0.0478369  0.40760553 0.96553266 0.84834695]], shape=(3, 5), dtype=float32)
tf.Tensor(
[[0.39882398 0.5428877  0.86151195]
 [0.9811106  0.9329668  0.0478369 ]
 [0.9230019  0.11001396 0.40760553]
 [0.77371573 0.7496586  0.96553266]
 [0.2190746  0.7730926  0.84834695]], shape=(5, 3), dtype=float32)


In [43]:
## tf.reshape : ex. 1D 벡터 --> 2D array
t = tf.zeros((30,))
print(t)

t_reshape = tf.reshape(t, shape=(5,6))
print(t_reshape)

tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.], shape=(30,), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(5, 6), dtype=float32)


In [50]:
## tf.squeeze() : 크기가 1인 차원은 없앤다. 
t = tf.zeros([1,2,1,3,1,1])
t_sq1 = tf.squeeze(t)
t_sq2 = tf.squeeze(t, [2,4])  ## 2~4 위치에 있는 1차원을 없앤다. 

print(t_sq1.shape, t_sq2.shape)

(2, 3) (1, 2, 3, 1)


In [54]:
## tf.expand_dims : tf.squeeze와 반대, 차원을 추가확장한다. 
image = tf.zeros([10,10,3])                 # 이미지의 가로x세로x채널 크기 
image_tf1 = tf.expand_dims(image, axis=0)   # axis에서 지정한 위치에 더미채널 1을 추가  
image_tf2 = tf.expand_dims(image, axis=1) 
image_tf3 = tf.expand_dims(image, axis=2) 

print(image_tf1.shape, image_tf2.shape, image_tf3.shape)

(1, 10, 10, 3) (10, 1, 10, 3) (10, 10, 1, 3)


---
#### 2. tensor에 수학연산 적용 
- tf.multiply(), tf.math.reduce_sum(), tf.math.reduce_mean(), tf.math.reduce_std()
- tf.linalg.matmul(), tf.norm() 
---

In [65]:
## 두개의 랜덤한 텐서 제작 
tf.random.set_seed(42)
t_1 = tf.random.uniform(minval = -1.0, maxval = 1.0, shape=(5,2))
t_2 = tf.random.normal(mean = 0, stddev = 1, shape=(5,2))

print(t_1, '\n', t_2)

tf.Tensor(
[[ 0.3291242  -0.11798644]
 [-0.294235   -0.07103491]
 [-0.9326792   0.3693447 ]
 [ 0.48023486  0.744889  ]
 [-0.5473473  -0.5536063 ]], shape=(5, 2), dtype=float32) 
 tf.Tensor(
[[ 8.4224582e-02 -8.6090374e-01]
 [ 3.7812304e-01 -5.1962738e-03]
 [-4.9453196e-01  6.1781919e-01]
 [-3.3082047e-01 -1.3840806e-03]
 [-4.2373410e-01 -1.3872087e+00]], shape=(5, 2), dtype=float32)


In [74]:
## t_1의 각 행에 대한 사칙연산 
print('-평균 =', tf.math.reduce_mean(t_1, axis = 0)) 
print('-표준편차 =', tf.math.reduce_std(t_1, axis = 0))
print('-합계 =', tf.math.reduce_sum(t_1, axis = 0)) 

## t_2의 각 열에 대한 사칙연산 
print('-평균 =', tf.math.reduce_mean(t_2, axis = 1)) 
print('-표준편차 =', tf.math.reduce_std(t_2, axis = 1))
print('-합계 =', tf.math.reduce_sum(t_2, axis = 1)) 

-평균 = tf.Tensor([-0.19298048  0.07432123], shape=(2,), dtype=float32)
-표준편차 = tf.Tensor([0.5308097  0.44477043], shape=(2,), dtype=float32)
-합계 = tf.Tensor([-0.9649024  0.3716061], shape=(2,), dtype=float32)
-평균 = tf.Tensor([-0.38833958  0.18646339  0.06164362 -0.16610228 -0.9054714 ], shape=(5,), dtype=float32)
-표준편차 = tf.Tensor([0.47256416 0.19165966 0.5561756  0.1647182  0.48173732], shape=(5,), dtype=float32)
-합계 = tf.Tensor([-0.77667916  0.37292677  0.12328723 -0.33220455 -1.8109428 ], shape=(5,), dtype=float32)


In [79]:
## tf.multuply() : 텐서의 곱. 대상 텐서들의 크기가 같아야 함 
tf.multiply(t_1, t_2)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 2.77203489e-02,  1.01574965e-01],
       [-1.11257032e-01,  3.69116839e-04],
       [ 4.61239666e-01,  2.28188246e-01],
       [-1.58871517e-01, -1.03098643e-03],
       [ 2.31929719e-01,  7.67967463e-01]], dtype=float32)>

In [81]:
## tf.linalg.matmul() : 행렬의 곱셈, matmul은 a의 기준에서 맨 마지막 axis에 대해서 b에 곱해줌. 이는 transpose_b=True와 동일함. 
## transpose_a, transpose_b : 해당되는 행렬을 전치해서 곱하라. 
print(tf.linalg.matmul(t_1, t_2, transpose_a = True))
print(tf.linalg.matmul(t_1, t_2, transpose_b = True))

tf.Tensor(
[[ 0.4507612  -0.0994221 ]
 [-0.23129272  1.0970688 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.12929532  0.12506254 -0.23565674 -0.10871772  0.02421068]
 [ 0.0363724  -0.11088791  0.10162187  0.09743728  0.22321764]
 [-0.39652476 -0.3545867   0.6894279   0.30803818 -0.11715022]
 [-0.60083014  0.17771722  0.22271523 -0.1599025  -1.2368084 ]
 [ 0.4305016  -0.20408794 -0.07134786  0.18183993  0.9998972 ]], shape=(5, 5), dtype=float32)


In [88]:
a = tf.constant(tf.random.uniform(shape=(1, 6, 10, 300)))
b = tf.constant(tf.random.uniform(shape=(1, 6, 10, 300)))
b_t = tf.transpose(b, perm=[0, 1, 3, 2])  # (1, 6, 300, 10)

print(tf.linalg.matmul(a, b_t).shape)
print(tf.linalg.matmul(a, b, transpose_b=True).shape)

(1, 6, 10, 10)
(1, 6, 10, 10)


- 선형대수에 대한 더 많은 공부 필요 .... 

--- 
#### 3. 텐서를 나누기, 쌓기, 연결하기 
- tf.split(), tf.stack(), tf.concat() 
--- 

In [94]:
## tf.split() : 동일한 크기의 텐서 리스트로 나누기 
tf.random.set_seed(1)
t = tf.random.uniform((6,))
print(t) 

tf.split(t, num_or_size_splits = 3)  ## 3개로 나누기 

tf.Tensor([0.16513085 0.9014813  0.6309742  0.4345461  0.29193902 0.64250207], shape=(6,), dtype=float32)


[<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.16513085, 0.9014813 ], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.6309742, 0.4345461], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.29193902, 0.64250207], dtype=float32)>]

In [113]:
t = tf.random.uniform((7,))
print(t) 
print('------------------------------------------------------------')
print(tf.split(t, num_or_size_splits = [4,3]))  ## 4,3개로 나누기 
print('------------------------------------------------------------')
print(tf.split(t, num_or_size_splits = [2,4,1]))  ## 2,4,1개로 나누기 

tf.Tensor(
[0.06265402 0.29493952 0.8037009  0.87552917 0.5866864  0.26796377
 0.67643046], shape=(7,), dtype=float32)
------------------------------------------------------------
[<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.06265402, 0.29493952, 0.8037009 , 0.87552917], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.5866864 , 0.26796377, 0.67643046], dtype=float32)>]
------------------------------------------------------------
[<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.06265402, 0.29493952], dtype=float32)>, <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.8037009 , 0.87552917, 0.5866864 , 0.26796377], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.67643046], dtype=float32)>]


In [117]:
## row 방향으로 합칠때 : tf.concat()
A = tf.ones((3,))
B = tf.zeros((2,))
print(A,'\n', B)

tf.concat([A,B], axis = 0)

tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32) 
 tf.Tensor([0. 0.], shape=(2,), dtype=float32)


<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 1., 1., 0., 0.], dtype=float32)>

In [120]:
## col 방향으로 합칠때 : tf.stack()
A = tf.ones((3,))
B = tf.zeros((3,))
print(A,'\n', B)

tf.stack([A,B], axis = 1)

tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32) 
 tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)>