## 4장. Numpy 기본 : 배열과 벡터연산 

In [3]:
# Numpy = Numerical Python, 일반 파이썬 배열계산에 비해 훨씬 빠르다. 
import numpy as np 
my_array = np.arange(1000000)
my_list = list(range(1000000)) 

In [6]:
%time for _ in range(10) : my_array2 = my_array*2 

Wall time: 26.9 ms


In [7]:
%time for _ in range(10) : my_list = [ x*2 for x in my_list]

Wall time: 1.16 s


In [8]:
# Numpy는 n차원 matrix(ndarray)를 기반으로 연산을 수행한다. 
data = np.random.randn(2, 3)  ## 2 x 3 matrix의 랜덤값 생성 
data 

array([[ 1.92186045,  0.0210223 , -0.46354935],
       [ 0.26580822, -0.28907786,  0.25689328]])

In [9]:
data * 10

array([[19.21860452,  0.21022299, -4.63549351],
       [ 2.65808225, -2.8907786 ,  2.56893281]])

In [10]:
data + data 

array([[ 3.8437209 ,  0.0420446 , -0.9270987 ],
       [ 0.53161645, -0.57815572,  0.51378656]])

In [13]:
# np.array : list --> matrix로 변환 
data2 = [[1,2,3,4],[5,6,7,8]]
array_2 = np.array(data2)
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
np.zeros((3,4))     ## zeros : 0으로 구성된 n x n matrix 생성 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((2,3))      ## ones : 1로 구성된 n x n matrix 생성 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
arr = np.arange(10)  ## 0~10의 배열을 만들어라 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
# arr2[2]   ## --> 2번째 obj인 [7,8,9]를 돌려준다. 
arr2[0, 2]  ## --> 0번째 obj의 2번째 값인 3을 돌려준다. 

3

In [28]:
np.sqrt(arr)  ## 제곱근 구하기 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [29]:
np.exp(arr)   ## 지수 구하기  <ex> ln(x) = 4 --> x = exp(4) = 54.6 

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [32]:
x = np.random.randn(10)
y = np.random.randn(10)
np.maximum(x, y)     ## x, y matrix의 각 원소별 max값 구하기 
# np.minimum(x, y)   ## x, y matrix의 각 원소별 min값 구하기

array([-0.26295704,  0.10707413,  0.07944812,  1.86745761,  0.42964223,
        1.21930368, -0.4240123 , -0.06250475,  0.53506673,  0.51547553])

In [36]:
#np.sum(x)     ## x 각 원소들의 합계 
#np.cumsum(x)  ## x 각 원소들의 누적 합계 
#np.mean(x)    ## x 각 원소들의 mean
#np.max(x)     ## x 각 원소들의 최대값
#np.min(x)     ## x 각 원소들의 최소값
#np.std(x)     ## x 각 원소들의 std
#np.var(x)     ## x 각 원소들의 분산
#np.log(x)     ## x 각 원소들의 log
#np.log10(x)   ## x 각 원소들의 상용로그 
#np.log2(x)    ## x 각 원소들의 log2x 

-1.5288395516461817

In [39]:
arr = np.random.randn(8)
arr.sort()      # matrix 원소들을 정렬한다. 
arr

array([-1.28603173, -0.78238111, -0.55279499,  0.06157974,  0.59598504,
        0.59922705,  0.95854237,  2.77131665])

In [56]:
arr = np.random.randn(3, 3)
arr

array([[-1.06280469,  0.60965566,  1.23363349],
       [-0.63938328,  1.00523758, -0.10240919],
       [-0.406943  ,  0.42405467,  0.77984667]])

In [57]:
arr.sort()    # matrix 원소들을 정렬한다. (row 단위로)
arr

array([[-1.06280469,  0.60965566,  1.23363349],
       [-0.63938328, -0.10240919,  1.00523758],
       [-0.406943  ,  0.42405467,  0.77984667]])

In [59]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)    ## unique : 중복제거 

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [61]:
ints = np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

In [10]:
#dot : 행렬의 곱셉
import numpy as np 
x = np.array([[1, 2, 3],[4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

In [9]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [11]:
np.dot(x, y)

array([[ 28,  64],
       [ 67, 181]])

In [13]:
#내장 random모듈이 한번에 하나의 랜덤을 얻는데 비해, 
#np.random은 분포를 지정하고 그로부터 여러개의 랜덤을 빠르게 얻을 수 있다. 
sample = np.random.normal(size=(4,4))
sample

array([[ 0.26235057,  0.56384109,  0.08135265,  3.94720563],
       [ 2.08289547, -0.63336121,  1.02510268,  1.60321131],
       [-0.82804162,  0.51519883, -1.20270868,  1.15034402],
       [ 0.33517078,  0.52496323, -0.70548093, -1.5769944 ]])

In [14]:
#난수 생성방법 
# 1) randn : mean = 0, sd = 1인 정규분포 
# 2) binomial : 이항분포 
# 3) normal :정규분포 
# 4) uniform : 균등분포 

In [31]:
sample2 = np.random.normal(60, 5.4, size=(4,4))
sample2

array([[68.08965019, 49.78355012, 56.54119691, 66.68525405],
       [63.15774519, 59.43329654, 58.61016777, 53.99698485],
       [64.20767447, 52.89021286, 56.96765928, 65.77832763],
       [65.22595362, 68.23373923, 57.80061478, 59.46854456]])

In [26]:
sample3 = np.random.uniform(1, 10, size=(4,4))
sample3

array([[1.41972344, 7.43983644, 9.34432814, 2.53974641],
       [9.91160479, 2.04505491, 3.42327406, 4.5076238 ],
       [2.25942325, 6.24949362, 5.66740866, 7.22760707],
       [1.1629148 , 4.61783037, 7.74489821, 2.40901976]])