---
### 1.1 벡터 만들기
---

In [7]:
import numpy as np

In [8]:
## 1개의 행 또는 열을 가진 벡터를 만들어라 

vector_row = np.array([1,2,3])
vector_col = np.array([[1], 
                       [2], 
                       [3]])

print(vector_row)
print(type(vector_row))

print(vector_col)
print(type(vector_row))

[1 2 3]
<class 'numpy.ndarray'>
[[1]
 [2]
 [3]]
<class 'numpy.ndarray'>


In [9]:
## copy the vector
new_row = vector_row.copy()
new_row

array([1, 2, 3])

---
### 1.2 행렬 만들기
---

In [13]:
## 2차원 행렬을 만들어라 
matrix = np.mat([
    [1,2], 
    [1,2], 
    [1,2]
])

matrix

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [11]:
print(type(matrix))

<class 'numpy.matrix'>


In [16]:
## zeros : 0으로 채워진 행렬을 만든다 
## ones : 1로 채워진 행렬을 만든다 
## full : 특정 값으로 채워진 행렬을 만든다 

zero_matrix = np.zeros((3,2))
one_matrix = np.ones([3,3])
seven_matrix = np.full((3,4), 7)

print(zero_matrix)
print(one_matrix)
print(seven_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


---
### 1.3 희소행렬 만들기 
- 데이터의 대부분이 0일때, sparse를 사용하여 0이 아닌 값들만을 가져와 행렬로 변환한다. 
- 머신러닝에 사용되는 데이터는 행렬의 대부분이 0인 경우가 많아, 이 방법을 사용하여 계산비용을 줄일 수 있다. 
---

In [17]:
from scipy import sparse

In [19]:
matrix2 = np.array([
    [0,0], 
    [0,1],
    [3,0]
])

matrix_sparse = sparse.csr_matrix(matrix2)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [20]:
matrix_large = np.array([
    [0,0,0,0,0,0,0,0,0,0], 
    [0,1,0,0,0,0,0,0,0,0], 
    [3,0,0,0,0,0,0,0,0,0]
])

matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [23]:
## 만약 희소행렬을 다시 matrix로 변환하려면, toarray를 사용 
matrix_large_sparse.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

---
### 1.4 원소 선택하기
- 파이썬의 indexing 규칙을 따른다.
---

In [25]:
vector = np.array([1,2,3,4,5,6,7])

In [32]:
print(vector[3]) 

print(matrix[2,1])

print(vector[:])

print(vector[:3])

print(vector[3:])

print(vector[:-1])

4
8
[1 2 3 4 5 6 7]
[1 2 3]
[4 5 6 7]
[1 2 3 4 5 6]


In [34]:
matrix = np.array([
    [1,2,3], 
    [4,5,6],
    [7,8,9]
])

In [39]:
print(matrix[:2, :])

print(matrix[:, 1:2])

[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]


In [42]:
matrix[[0,2]] ## 매트릭스의 row=0 & 2

array([[1, 2, 3],
       [7, 8, 9]])

In [44]:
## 매트릭스에서 해당 위치의 것을 추출 
matrix[
    [0,2], 
    [1,0] ]

array([2, 7])

In [45]:
## 연산자를 이용한 추출 
matrix[matrix > 5]

array([6, 7, 8, 9])

---
### 1.5 행렬정보 확인하기
---

In [47]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
matrix.shape

(3, 3)

In [49]:
matrix.size

9

In [51]:
matrix.ndim

2

In [52]:
matrix.dtype

dtype('int32')

In [53]:
matrix.nbytes   ## 매트릭스의 데이터 크기(바이트수)

36

---
### 1.6 벡터화 연산 적용하기
- vectorize를 사용하여 매트릭스에 특정 함수를 적용한다. 
---

In [54]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
## 함수 생성 
vectorized_add_100 = np.vectorize(lambda i : i + 100)

In [57]:
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [59]:
## 보다 간단한 방법 : broadcasting 
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [60]:
## 행방향으로 더하기 
matrix + [10, 20, 30]

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [61]:
## 열방향으로 더하기 
matrix + [
    [10], 
    [20], 
    [30]
]

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39]])

---
### 1.7 min, max 찾기
---

In [62]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
print("Minimum Value =", np.min(matrix))
print("Maximum Value =", np.max(matrix))

Minimum Value = 1
Maximum Value = 9


In [70]:
## 각 col, row 에서의 min/max 구하기 
print( np.min(matrix, axis = 0) )
print( np.max(matrix, axis = 1) )

[1 2 3]
[3 6 9]


---
### 1.8 mean, var, std
---

In [71]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
print( "Mean =", np.mean(matrix) )
print( "Var =", np.var(matrix) )
print( "Stdev =", np.std(matrix) )

Mean = 5.0
Var = 6.666666666666667
Stdev = 2.581988897471611


In [76]:
## 각 col, row 에서의 통계량 구하기 
print( np.mean(matrix, axis = 0) )
print( np.mean(matrix, axis = 1) )

[4. 5. 6.]
[2. 5. 8.]


---
### 1.9 배열 크기 바꾸기
- reshape : 행과 열을 서로 바꾼다 
---

In [77]:
matrix_new = np.array([
    [1,2,3], 
    [4,5,6], 
    [7,8,9],
    [10,11,12]
])

matrix_new

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [79]:
matrix_new.reshape(2,6)  ## 원소의 총 갯수는 일치해야 한다.

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [80]:
matrix_new.reshape(-1)  ## -1은 1차원 배열로 변경 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

---
### 1.10 벡터 및 행렬 전치하기 
- transpose
---

In [81]:
matrix_new

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
matrix_new.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [84]:
np.array([
    [1,2,3,4,5,6,7]
])

array([[1, 2, 3, 4, 5, 6, 7]])

In [85]:
np.array([
    [1,2,3,4,5,6,7]
]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

---
### 1.17 벡터간 곱하기  
- matmul, @ 
---

In [92]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

np.matmul(vector_a, vector_b)

32

In [95]:
## matmul을 간단하기 @로 대체 가능 
vector_a @ vector_b

32

---
### 1.18 행렬의 덧셈, 뺄셈
### 1.19 행렬의 곱셈
---

In [96]:
matrix_a = np.array([
    [1,1,1], 
    [1,1,1],
    [1,1,2]
])

matrix_b = np.array([
    [1,3,1], 
    [1,3,1], 
    [1,3,8]
])

In [97]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [98]:
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [99]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [100]:
matrix_a - matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [101]:
np.matmul(matrix_a, matrix_b)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [102]:
matrix_a @ matrix_b

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [103]:
## 주의!! 원소별 곱셈을 할때는 *를 사용 
matrix_a * matrix_b

array([[ 1,  3,  1],
       [ 1,  3,  1],
       [ 1,  3, 16]])

---
### 1.21 난수 생성
---

In [113]:
np.random.random(3) ## 3개의 난수 생성 (0~1사이)

array([0.38344152, 0.79172504, 0.52889492])

In [114]:
## 1~10 사이의 정수 난수 5개를 만들어라 
np.random.randint(0, 11, 5)

array([8, 1, 5, 9, 8])

In [115]:
## mean = 0, std = 1.0인 정규분포에서 난수 만들기 
np.random.normal(0, 1.0, 3)

array([ 0.48431215,  0.57914048, -0.18158257])

In [117]:
## 1 to 5의 값을 가진 uniform 분포에서 난수 만들기 
np.random.uniform(1, 5, 4)

array([4.77867567, 3.08739329, 2.65864776, 2.05822245])

In [122]:
## 표준정규분포로 부터 5x3 난수행렬 만들기 (mean=0, std=1)
np.random.standard_normal((5,3))

array([[-0.45792242,  0.4253934 , -0.02797118],
       [ 1.47598983,  0.6467801 , -0.36433431],
       [-0.67877739, -0.35362786, -0.74074747],
       [-0.67502183, -0.13278426,  0.61980106],
       [ 1.79116846,  0.17100044, -1.72567135]])

In [126]:
## cf. choic : 배열에서 랜덤하게 지정한 갯수만큼 숫자를 뽑는다 
np.random.choice([3, 5, 9, 1, 0 ], 2)

array([5, 0])

In [133]:
## cf. shuffle : 배열을 섞는다. 
x1 = np.array([1,2,3,4,5,6,7])

np.random.shuffle(x1)
x1

array([2, 7, 5, 4, 3, 1, 6])