### 03. Multivariable Linear Regression
    - 3가지 입력값으로 부터 1개의 결과값을 예측하는 문제(다중회귀)

In [10]:
## load the libaries 
import torch 
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim 

In [11]:
## data 
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

print(y_train)

tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])


In [34]:
## 모형 초기화 
w1 = torch.zeros(1, requires_grad = True)
w2 = torch.zeros(1, requires_grad = True)
w3 = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)

## optimizer 
optimizer = optim.SGD([w1, w2, w3, b], lr = 0.00001)

## model training 
nb_epochs = 1000
for epoch in range(nb_epochs+1): 
    hypothesis = x1_train*w1 + x2_train*w2 + x3_train*w3 + b
    cost = torch.mean((hypothesis-y_train)**2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    ## print the result 
    if epoch % 100 == 0 : 
        print(
            'epoch {:4d}/{} | w1: {:.3f} | w2: {:.3f} | w3: {:.3f} | b: {:.3f} | cost: {:.3f}'.format(
                epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item() 
            )
        )

epoch    0/1000 | w1: 0.294 | w2: 0.294 | w3: 0.297 | b: 0.003 | cost: 29661.801
epoch  100/1000 | w1: 0.674 | w2: 0.661 | w3: 0.676 | b: 0.008 | cost: 1.564
epoch  200/1000 | w1: 0.679 | w2: 0.655 | w3: 0.677 | b: 0.008 | cost: 1.498
epoch  300/1000 | w1: 0.684 | w2: 0.649 | w3: 0.677 | b: 0.008 | cost: 1.435
epoch  400/1000 | w1: 0.689 | w2: 0.643 | w3: 0.678 | b: 0.008 | cost: 1.376
epoch  500/1000 | w1: 0.694 | w2: 0.638 | w3: 0.678 | b: 0.009 | cost: 1.320
epoch  600/1000 | w1: 0.699 | w2: 0.633 | w3: 0.679 | b: 0.009 | cost: 1.266
epoch  700/1000 | w1: 0.704 | w2: 0.627 | w3: 0.679 | b: 0.009 | cost: 1.216
epoch  800/1000 | w1: 0.709 | w2: 0.622 | w3: 0.679 | b: 0.009 | cost: 1.168
epoch  900/1000 | w1: 0.713 | w2: 0.617 | w3: 0.680 | b: 0.009 | cost: 1.122
epoch 1000/1000 | w1: 0.718 | w2: 0.613 | w3: 0.680 | b: 0.009 | cost: 1.079


- 위의 코드를 좀더 간략하게 만들어 보자. 
    - train x1, x2, x3를 하나의 matrix로 만들고, matmul을 이용하여 계산한다.

In [47]:
## data를 좀더 간략하게 
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

## 모형 초기화, optimizer 설정도 간략하게 가능 
w = torch.zeros((3,1), requires_grad = True)  ## w는 3x1의 매트릭스 
b = torch.zeros(1, requires_grad = True)      ## b는 1의 매트릭스
optimizer = optim.SGD([w, b], lr= 0.00001)

nb_epochs = 20
for epoch in range(nb_epochs+1): 
    hypothesis = x_train.matmul(w)+b    ##모형을 간략하게 표현 
    cost = torch.mean((hypothesis-y_train)**2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    ## print the result (if문 사용할 필요 없음))
    ## hypothesis 출력을 깨끗하게 하기 위해, squeeze(세로행렬을 가로 변환) 와 detach(불필요한 정보 삭제) 사용    
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))   

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) Cost: 9298.520508
Epoch    2/20 hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) Cost: 2915.712402
Epoch    3/20 hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) Cost: 915.040649
Epoch    4/20 hypothesis: tensor([137.7967, 165.6247, 163.1911, 177.7112, 126.3307]) Cost: 287.936157
Epoch    5/20 hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) Cost: 91.371010
Epoch    6/20 hypothesis: tensor([148.1035, 178.0143, 175.3980, 191.0042, 135.7812]) Cost: 29.758249
Epoch    7/20 hypothesis: tensor([150.1744, 180.5042, 177.8509, 193.6753, 137.6805]) Cost: 10.445281
Epoch    8/20 hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) Cost: 4.391237
Epoch    9/20 hypothesis: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) Cost: 2.493121
Epoch   10/20 hypo

- 실전에서 쓰이는 코드 
    - torch.nn, torch.nn.functional 모듈을 사용하여 코드를 간단하게 만든다. 

In [52]:
## input = 3 & output = 1을 처리하는 모델을 class로 선언한다. 
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [96]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

## class에서 정의한 모델을 사용함 
model = MultivariateLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr= 1e-5)

nb_epochs = 20
for epoch in range(nb_epochs+1):     
    ## 모델을 사용하여 데이터를 훈련시켜라 
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} Cost: {:.4f}'.format(
        epoch, nb_epochs, cost.item()
    ))  

Epoch    0/20 Cost: 7561.7314
Epoch    1/20 Cost: 2371.3164
Epoch    2/20 Cost: 744.3956
Epoch    3/20 Cost: 234.4428
Epoch    4/20 Cost: 74.5989
Epoch    5/20 Cost: 24.4958
Epoch    6/20 Cost: 8.7907
Epoch    7/20 Cost: 3.8676
Epoch    8/20 Cost: 2.3239
Epoch    9/20 Cost: 1.8395
Epoch   10/20 Cost: 1.6873
Epoch   11/20 Cost: 1.6391
Epoch   12/20 Cost: 1.6235
Epoch   13/20 Cost: 1.6182
Epoch   14/20 Cost: 1.6160
Epoch   15/20 Cost: 1.6149
Epoch   16/20 Cost: 1.6140
Epoch   17/20 Cost: 1.6133
Epoch   18/20 Cost: 1.6126
Epoch   19/20 Cost: 1.6120
Epoch   20/20 Cost: 1.6113


In [97]:
print('Final Result')
print('1. Weights & bias:', prediction.squeeze().detach())
print('2. Cost:', cost.detach())

Final Result
1. Weights & bias: tensor([152.7227, 183.7155, 180.8768, 197.1936, 140.0789])
2. Cost: tensor(1.6113)


- 참고) 데이터를 load하여 모델 훈련 시키기 

In [102]:
import numpy as np 
xy = np.loadtxt('data/data-01-test-score.csv', delimiter=',', dtype=np.float32)
print(xy[:5])
print(xy.shape)

[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]]
(25, 4)


In [109]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]  ## y_data = xy[:, -1]이 아님에 주의!!
print(x_data[:5])
print(y_data[:5])

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [110]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [113]:
## numpy arrary를 tensor로써 가져온다. 
x_data_train = torch.FloatTensor(x_data)
y_data_train = torch.FloatTensor(y_data)

model = MultivariateLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr= 1e-5)

nb_epochs = 21
for epoch in range(nb_epochs+1):     
    prediction = model(x_data_train)
    cost = F.mse_loss(prediction, y_data_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} Cost: {:.4f}'.format(
        epoch, nb_epochs, cost.item()
    ))  

Epoch    0/21 Cost: 20543.7500
Epoch    1/21 Cost: 7601.6450
Epoch    2/21 Cost: 2816.5884
Epoch    3/21 Cost: 1047.4189
Epoch    4/21 Cost: 393.3061
Epoch    5/21 Cost: 151.4607
Epoch    6/21 Cost: 62.0419
Epoch    7/21 Cost: 28.9792
Epoch    8/21 Cost: 16.7532
Epoch    9/21 Cost: 12.2309
Epoch   10/21 Cost: 10.5571
Epoch   11/21 Cost: 9.9363
Epoch   12/21 Cost: 9.7049
Epoch   13/21 Cost: 9.6174
Epoch   14/21 Cost: 9.5832
Epoch   15/21 Cost: 9.5687
Epoch   16/21 Cost: 9.5614
Epoch   17/21 Cost: 9.5568
Epoch   18/21 Cost: 9.5532
Epoch   19/21 Cost: 9.5501
Epoch   20/21 Cost: 9.5470
Epoch   21/21 Cost: 9.5440


In [115]:
print('Final Result')
print('1. Weights & bias:', prediction.detach())
print('2. Cost:', cost.detach())

Final Result
1. Weights & bias: tensor([[155.1230],
        [183.3790],
        [182.2354],
        [199.1230],
        [138.5018],
        [102.6612],
        [150.8056],
        [114.3663],
        [171.4164],
        [159.8771],
        [143.7053],
        [140.5620],
        [187.5747],
        [154.7676],
        [151.1049],
        [186.9828],
        [145.6467],
        [182.1534],
        [179.1929],
        [160.7616],
        [176.2131],
        [172.8384],
        [168.0769],
        [154.7841],
        [190.2478]])
2. Cost: tensor(9.5440)
