### Lec 08-1: 딥러닝의 기본 개념- 시작과 XOR 문제

- 외부의 자극(x)에 가중치(W)와 바이어스(b)가 부여된 값(WX +b)가 뉴런에 입력되고, 
- 그 값이 특정 임계치 이상인 경우 신경망을 통해 전달된다. 

<left><img src= 'img/neuron.PNG' width="40%"></left>

- 1차 침체기 : and/or을 linear 방식으로 풀수 있으나, xor은 풀수 없다는것이 증명됨

<left><img src= 'img/xor.PNG' width="30%"></left>

- Backpropagation과 CNN(convolution Neural network)에 대한 아이디어가 나오면서 극복되는 듯 했으나, 

<left><img src= 'img/backp.PNG' width="45%"></left>
- Backpropagation의 한계, layer가 많을 경우 뒤에서부터 멀리 떨어진 layer의 W와 b를 변경할 수 없다는 한계로, 머신러닝 분야의 두 번째 침체기를 맞음 

<left><img src= 'img/bigp.PNG' width="50%"></left>

### Lec 08-2: 딥러닝의 기본 개념- Back propagation과 2006/2007 '딥'의 출현 

##### <font color = 'yellow'> 새로운 연구결과 </font>
- 여러 개의 layer가 있어도 초기값을 잘 선택하면 학습이 가능하다.
- 신경망을 잘 구성하면 복잡한 문제를 효율적으로 풀 수 있다.
- Neural Network 대신 사람들의 주의를 끌 수 있는 Deep Learning으로 rebranding
##### --> ImageNet 경진대회에서 한 대학원생이 AlexNet으로 획기적인 성능 향상으로, 관심을 끌어올림 

##### <font color = 'yellow'> 지금까지 neural network가 잘 작동하지 않았던 이유는... </font>
- labeled 데이터셋이 너무 작았고,
- 컴퓨터는 수백만 배 느렸다.
- 초기화를 잘 하지 못했고,
- non-linearity(sigmoid)를 잘못 사용했다. 

### Lab 08: Tensor manipulation

##### <font color = 'yellow'> 선형대수 기초 : Tensor(arrary)를 자유자재로 다루기  </font>

- 1) shape, rank, axix의 개념 
- 2) 행렬계산에서 matmul과 multiply의 차이
- 3) reduce_mean, reduce_sum, argmax 계산시 axis 지정
- 4) reshape, squeeze, expand_dims
- 5) one_hot, cast, stack 
- 6) ones like, zero like
- 7) zip

In [36]:
import numpy as np

import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
sess = tf.InteractiveSession()

In [37]:
#### rank는 차원의 수, shape는 요소의 수를 의미한다. 
#### cf.차원의 갯수는 중괄호의 갯수와 같음 

x1 = [1., 2., 3.]                  # Rank = 1 , Shape = [3]

x2 = [[1., 2., 3.], 
      [4., 5., 6.]]                # Rank = 2, Shape = [2, 3]

x3 = [
       [[1., 2., 3.]], 
       [[7., 8., 9.]]
      ]                            # Rank = 3, Shape = [2, 1, 3]

print(np.array(x1).ndim, np.array(x1).shape)
print(np.array(x2).ndim, np.array(x2).shape)    ### 2x3 matrix 
print(np.array(x3).ndim, np.array(x3).shape)    ### 2x(1x3) matrix 

1 (3,)
2 (2, 3)
3 (2, 1, 3)


In [38]:
matrix1 = tf.constant( [ [1. , 2.], [3., 4.] ] )
matrix2 = tf.constant( [ [1.], [2.] ] )

print(matrix1.shape, matrix2.shape)

tf.matmul(matrix1, matrix2).eval()

(2, 2) (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

- matrix1, 2 모두 rank=2 이므로, shape는 [  ,  ] 형태가 됨 
- matrix1은 2x2 매트릭스, matrix2는 2x1 매트릭스임 
- matmul(matrix multiply)의 결과는, 1x1 + 2x2 = 5 & 3x1 + 4x2 = 11 이 된다.

In [43]:
#### 주의! 매트릭스 곱(matmul)과 일반행렬의 곱셈(multiply)는 다르다. 
#### 일반연산은 broadcasting이 적용되어 shape에 상관없이 계산이 이뤄진다
print((matrix1*matrix2).eval())
print('-------------------------')
print((matrix1+matrix2).eval())

[[1. 2.]
 [6. 8.]]
-------------------------
[[2. 3.]
 [5. 6.]]


In [46]:
#### axis = 0은 컬럼방향(세로), 1은 행방향(가로)으로 연산한다.  
#### axis = -1은 가장 안쪽의 것에 대해 세로방향을 의미한다. 
x = [ [1. , 2.], 
      [3. , 4.]  ]

print( tf.reduce_mean(x).eval() )              ## (1 + 2 + 3 + 4) / 4 = 2.5 
print( tf.reduce_mean(x, axis = 0).eval() )    ## (1 + 3) / 2 = 2 , (2 + 4) / 2 = 3 
print( tf.reduce_mean(x, axis = 1).eval() )    ## (1 + 2 ) / 2 = 1.5 , (3 + 4) / 2 = 3.5 
print( tf.reduce_mean(x, axis = -1).eval() )    ## (1 + 2 ) / 2 = 1.5 , (3 + 4) / 2 = 3.5 

print('---------------------------------------')

print( tf.reduce_sum(x).eval() )              ## 1 + 2 + 3 + 4 = 10
print( tf.reduce_sum(x, axis = 0).eval() )    ## 1 + 3 = 4 , 2 + 4 = 6 
print( tf.reduce_sum(x, axis = 1).eval() )    ## 1 + 2 = 3 , 3 + 4 = 7
print( tf.reduce_sum(x, axis = -1).eval() )    ## 1 + 2 = 3 , 3 + 4 = 7

2.5
[2. 3.]
[1.5 3.5]
[1.5 3.5]
---------------------------------------
10.0
[4. 6.]
[3. 7.]
[3. 7.]


In [52]:
#### arg_max : 가장 큰 값의 위치(index)를 말하라
x2 = [ [0,1,2], 
       [2,1,0] ]

print( tf.argmax(x2, axis = 0).eval() )
print( tf.argmax(x2, axis = 1).eval() )
print( tf.argmax(x2, axis = -1).eval() )

[1 0 0]
[2 0]
[2 0]


- 파이썬 NumPy 에서 배열의 차원(Dimension)을 재구조화, 변경하고자 할 때 reshape() 메소드를 사용합니다.  
- 가령, 3개의 행과 4개의 열로 구성된 2차원의 배열로 재설정하고 싶으면 reshape(3, 4) 처럼 reshape()의 매개변수로 변경하고자 하는 배열의 행과 열의 차원을 정수로 입력해주면 됩니다. 
- 그런데 reshape(-1, 2) 혹은 reshape(3, -1) 처럼 reshape() 메소드 안에 '-1'이 들어가 있는 경우가 있습니다. 
- 이때 reshape()의 '-1'이 의미하는 바는, 변경된 배열의 '-1' 위치의 차원은 "원래 배열의 길이와 남은 차원으로 부터 추정"이 된다는 뜻입니다. (알아서 하라는 뜻)

In [53]:
#### reshape 
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape   ## [ 2 , 2 , 3 ]

(2, 2, 3)

In [54]:
#### n x 3 매트릭스로 reshape 하라 
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
#### n x (1 x 3) 매트릭스로 reshape 하라 
tf.reshape(t, shape = [-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

- squeeze는 차원 중 사이즈가 1인 것을 찾아 스칼라값으로 바꿔 해당 차원을 제거한다.
- expand_dims는 axis로 지정된 차원을 추가한다.

In [58]:
tf.squeeze( [[0],[1],[2]] ).eval()

array([0, 1, 2])

In [59]:
tf.expand_dims( [0,1,2], 1 ).eval() 

array([[0],
       [1],
       [2]])

- one-hot(원핫)인코딩이란? 단 하나의 값만 True이고 나머지는 모두 False인 인코딩을 말한다.
- 즉, 1개만 Hot(True)이고 나머지는 Cold(False)이다.
- 예를들면 [0, 0, 0, 0, 1]이다. 5번째(Zero-based 인덱스이므로 4)만 1이고 나머지는 0이다.

In [63]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()
#### 첫번째부터 index = 0이 true, 두번째는 index = 1이 true, .... 
#### 0~2의 3가지 숫자로 구성되었으므로, depth = 3 이다. 

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [61]:
#### one_hot 연산시 rank하나가 증가하기 때문에, 보통 reshape를 통해서 아래와 같이 만들어 준다. 
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

- tf.cast : 텐서를 새로운 형태로 캐스팅하는데 사용한다.
- 부동소수점형에서 정수형으로 바꾼 경우 소수점 버림을 한다.
- Boolean형태인 경우 True이면 1, False이면 0을 출력한다.

In [64]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [65]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

- tf.stack : 여러 조각의 행렬을 합칠 때 사용

In [66]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
#### 축의 방향을 바꿔서 쌓는다. (앞서 stack의 결과물을 transpose 하는 것)
tf.stack([x, y, z], axis = 1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

- tf.ones_like(x) : 매트릭스 x와 동일한 shape로, 1으로 채워진 매트릭스를 만든다. 
- tf.zeros_like(x) : 매트릭스 x와 동일한 shape로, 0으로 채워진 매트릭스를 만든다. 

In [70]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [71]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

- zip() 은 동일한 개수로 이루어진 자료형을 묶어 주는 역할을 하는 함수이다.

In [73]:
### 두 매트릭스를 각각 x, y에 할당하여 한번에 처리한다. 
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [74]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
