### Lec 05-1: Logistic Classification

##### <font color = 'yellow'> - Logistic Hypothesis </font>
##### 시그모이드(sigmoid) 함수는 앞에서 배운 공식(Wx + b )이 만들어 내는 값을 0과 1 사이의 값으로 변환한다. 

##### - e로 시작하는 계산식이 0일 때, 1/1이 되어서 최대값인 1이 된다.
##### - e로 시작하는 계산식이 매우 클 때, (1/큰수)이 되어서 최소값인 0이 된다.
##### - WX가 0일 때, 지수가 0이 되어, 분모는 2가 되고, 이때 중간값인 1/2이 된다.
<left><img src= 'img/sigmoid.PNG' width="50%"></left>

### Lec 05-2: Cost function of Logistic Regression 

##### <font color = 'yellow'>  - 가설 H(x)가 지수형태이므로, log를 씌워 경사하강법을 사용할 수 있도록 변환한다. </font>
<left><img src= 'img/logistic_cost_function.PNG' width="50%"></left>

<left><img src= 'img/logistic_gradient_descent_algorithm.PNG' width="50%"></left>

### Lab 05: Logistic Classification with tf

In [2]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


##### <font color = 'yellow'>  - reference code </font>
<left><img src= 'img/code_logistic.PNG' width="80%"></left>

In [26]:
#### data set 
x_data = [[1, 2], 
          [2, 3], 
          [3, 1], 
          [4, 3], 
          [5, 3], 
          [6,2]]
y_data = [[0], 
          [0], 
          [0], 
          [1], 
          [1], 
          [1]]

X = tf.placeholder(tf.float32, shape = [None, 2])
Y = tf.placeholder(tf.float32, shape = [None, 1])
W = tf.Variable(tf.random_normal([2, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.sigmoid(tf.matmul(X, W)+b)    #### sigmoid와 matmul은 간단하게 로지스틱 함수를 만들어 준다 
cost = -tf.reduce_mean( Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))   #### logistic cost 함수 

train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)  #### logistic cost 함수를 최소화 방향으로 학습 

#### hypothesis가 0.5 이상이면 pass, 0.5 미만이면 fail 
#### tf.cast함수 : 텐서를 새로운 형태로 캐스팅하는데 사용한다. Boolean형태인 경우 True이면 1, False이면 0을 출력한다.
predicted = tf.cast(hypothesis > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.float32))

#### graphing 
sess = tf.Session()
sess.run(tf.global_variables_initializer())
    
for step in range(10001): 
    cost_val, _ = sess.run( [cost, train], feed_dict = {X:x_data, Y:y_data}  )
    if step % 1000 == 0 : 
        print(step, cost_val) 

0 1.3695116
1000 0.43565235
2000 0.3679743
3000 0.3157927
4000 0.2749644
5000 0.24266042
6000 0.21673547
7000 0.1956126
8000 0.178147
9000 0.16350637
10000 0.15107986


In [33]:
#### accuracy report 
h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict = {X:x_data, Y:y_data} )
print('hypothesis :', '\n', h)
print('predicted :', '\n', c)
print('accuracy :', '\n', a)

#### 작업이 끝나면 세션을 수동 종료
sess.close()

hypothesis : 
 [[0.03140939]
 [0.1597431 ]
 [0.30805475]
 [0.7799301 ]
 [0.9386564 ]
 [0.97986126]]
predicted : 
 [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]
accuracy : 
 1.0


#### <font color = 'yellow'>Practice : 당뇨병 예측하기 </font>

In [85]:
#### data loading 
import numpy as np 
import pandas as pd 

xy = pd.read_csv('data/data-03-diabetes.csv', header = None)
print(xy.shape)
xy.head()

(759, 9)


0         1         2         3         4         5         6  \
0 -0.294118  0.487437  0.180328 -0.292929  0.000000  0.001490 -0.531170   
1 -0.882353 -0.145729  0.081967 -0.414141  0.000000 -0.207153 -0.766866   
2 -0.058824  0.839196  0.049180  0.000000  0.000000 -0.305514 -0.492741   
3 -0.882353 -0.105528  0.081967 -0.535354 -0.777778 -0.162444 -0.923997   
4  0.000000  0.376884 -0.344262 -0.292929 -0.602837  0.284650  0.887276   

          7  8  
0 -0.033333  0  
1 -0.666667  1  
2 -0.633333  0  
3  0.000000  1  
4 -0.600000  0

In [88]:
#### x, y data 구분 
x_data = xy.loc[:, 0:7]
y_data = xy.loc[:, [8]]

print(x_data.shape)
print(y_data.shape)

x_data = x_data.astype('float32').copy()
y_data = y_data.astype('float32').copy()

#x_data.head()
y_data.head()

(759, 8)
(759, 1)


8
0  0.0
1  1.0
2  0.0
3  1.0
4  0.0

In [103]:
X = tf.placeholder(tf.float32, shape = [None, 8])
Y = tf.placeholder(tf.float32, shape = [None, 1])
W = tf.Variable(tf.random_normal([8, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)    #### sigmoid와 matmul은 간단하게 로지스틱 함수를 만들어 준다 
cost = -tf.reduce_mean( Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))   #### logistic cost 함수 

train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)  #### logistic cost 함수를 최소화 방향으로 학습 

#### hypothesis가 0.5 이상이면 pass, 0.5 미만이면 fail 
predicted = tf.cast(hypothesis > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.float32))

#### graphing 
sess = tf.Session()
sess.run(tf.global_variables_initializer())
feed = {X:x_data, Y:y_data}
    
for step in range(10001): 
    sess.run( train, feed_dict = feed  )
    if step % 1000 == 0 : 
        print(step, sess.run(cost, feed_dict = feed) )

print('-------------------------------------------------------------')        

#### accuracy report 
h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict = feed )
print('hypothesis :', '\n', h[-5:] )
print('predicted :', '\n', c[-5:] )
print('accuracy :', '\n', a)

#### 작업이 끝나면 세션을 수동 종료
sess.close()

0 1.1100742
1000 0.6148637
2000 0.55790335
3000 0.5280902
4000 0.5111319
5000 0.5006832
6000 0.49380934
7000 0.48904964
8000 0.48562062
9000 0.4830724
10000 0.48113146
-------------------------------------------------------------
hypothesis : 
 [[0.7478162]
 [0.6914754]
 [0.8116734]
 [0.741308 ]
 [0.8833011]]
predicted : 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
accuracy : 
 0.76943344
