### Lec 04: Multivariable Linear Regression

##### <font color = 'yellow'> - Hypothesis using Matrix  </font>
<left><img src= 'img/matrix.PNG' width="32.6%"></left>
<left><img src= 'img/matrix_n.PNG' width="50%"></left>

### Lec 04-1: Multivariable Linear Regression with tf

In [5]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


##### @@ matrix 
<left><img src= 'img/score.PNG' width="20%"></left>

In [13]:
#### 3회의 중간시험 점수를 바탕으로, 최종 점수를 예측하라 
x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data = [152, 185, 180, 196, 142]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'wieght1')
w2 = tf.Variable(tf.random_normal([1]), name = 'wieght2')
w3 = tf.Variable(tf.random_normal([1]), name = 'wieght3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b

#### cost function & graphing 
cost = tf.reduce_mean( tf.square(hypothesis - Y) )
optimizer = tf.train.GradientDescentOptimizer(learning_rate= 1e-5)  ### 1e의 -5승(= 0.00001)
train = optimizer.minimize(cost)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001) : 
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                    feed_dict = {x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 200 == 0 :
        #print(step, 'cost: ', cost_val, '\n prediction: \n', hy_val)
        print(step, cost_val, hy_val)

0 8179.901 [79.45925 83.16678 88.61679 91.08252 65.13148]
200 20.921246 [159.25803 179.7165  183.41571 194.37343 138.88565]
400 19.134533 [158.93677 179.9349  183.31491 194.31883 139.1568 ]
600 17.527744 [158.632   180.14201 183.2192  194.26787 139.41316]
800 16.082844 [158.34294 180.33833 183.12827 194.22026 139.6555 ]
1000 14.783037 [158.06871 180.52449 183.04189 194.17586 139.88454]
1200 13.613493 [157.80853 180.70099 182.95981 194.13448 140.10098]
1400 12.560989 [157.56175 180.8684  182.88191 194.09602 140.30556]
1600 11.613227 [157.32753 181.02711 182.80782 194.06029 140.49886]
1800 10.759722 [157.10532 181.1777  182.73749 194.02716 140.68149]
2000 9.99066 [156.8944  181.32051 182.67053 193.9964  140.85396]


##### <font color = 'yellow'> * 코드가 매우 복잡하다. 매트릭스를 적용해보자!! </font>

In [20]:
#### data를 matrix 형식으로 입력 
x_data = [[73, 80, 75], 
          [93, 88, 93], 
          [89, 91, 90], 
          [96, 98, 100], 
          [73, 66, 70]]

y_data = [[152],
          [185], 
          [180], 
          [196], 
          [142]] 

X = tf.placeholder(tf.float32, shape = [None, 3])   ### None는 N개의 row를 의미함 
Y = tf.placeholder(tf.float32, shape = [None, 1])   ### row는 그냥 None로 두고, 컬럼수(3, 1)만 지정해 주면 된다. 

W = tf.Variable(tf.random_normal([3, 1]), name = 'wieght')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b

#### cost function & graphing 
cost = tf.reduce_mean( tf.square(hypothesis - Y) )
optimizer = tf.train.GradientDescentOptimizer(learning_rate= 1e-5)  ### 1e의 -5승(= 0.00001)
train = optimizer.minimize(cost)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001) : 
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                    feed_dict = {X: x_data, Y: y_data})
    if step >= 1995 :        
        print(step, cost_val, hy_val) 

1995 15.775301 [[156.77208]
 [180.94463]
 [182.15988]
 [198.04233]
 [136.44829]]
1996 15.76697 [[156.77057]
 [180.94568]
 [182.15944]
 [198.04199]
 [136.44968]]
1997 15.7586 [[156.76904]
 [180.94672]
 [182.15898]
 [198.04163]
 [136.45107]]
1998 15.7502165 [[156.76752]
 [180.94775]
 [182.15851]
 [198.04126]
 [136.45245]]
1999 15.7419 [[156.766  ]
 [180.94879]
 [182.15804]
 [198.0409 ]
 [136.45383]]
2000 15.733566 [[156.7645 ]
 [180.94984]
 [182.15758]
 [198.04056]
 [136.45522]]


### Lec 04-2: Reading the data from file 

In [21]:
import numpy as np

In [27]:
xy = np.loadtxt('data/data-10-test-score.csv', delimiter = ',', dtype = np.float32)
xy

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.]], dtype=float32)

In [30]:
x_data = xy[ :, 0:-1 ]  ## xy전체에서, 인덱스 0 ~ -1(마지막)의 직전까지 가져와라 
y_data = xy[ :, [-1] ]  ## xy전체에서, 마지막 컬럼을 가져와라 

print(x_data)
print('----------------------------------------')
print(y_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]]
----------------------------------------
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [36]:
#import numpy as np
#import tensorflow as tf
tf.set_random_seed(777)

xy = np.loadtxt('data/data-10-test-score.csv', delimiter = ',', dtype = np.float32)
x_data = xy[ :, 0:-1 ]  ## xy전체에서, 인덱스 0 ~ -1(마지막)의 직전까지 가져와라 
y_data = xy[ :, [-1] ]  ## xy전체에서, 마지막 컬럼을 가져와라 

print(x_data.shape, y_data.shape)
print('----------------------------------------')
print(x_data)
print('----------------------------------------')
print(y_data)

(6, 3) (6, 1)
----------------------------------------
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]]
----------------------------------------
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [37]:
X = tf.placeholder(tf.float32, shape = [None, 3])   ### None는 N개의 row를 의미함 
Y = tf.placeholder(tf.float32, shape = [None, 1])   ### row는 그냥 None로 두고, 컬럼수(3, 1)만 지정해 주면 된다. 

W = tf.Variable(tf.random_normal([3, 1]), name = 'wieght')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b

#### cost function & graphing 
cost = tf.reduce_mean( tf.square(hypothesis - Y) )
optimizer = tf.train.GradientDescentOptimizer(learning_rate= 1e-5)  ### 1e의 -5승(= 0.00001)
train = optimizer.minimize(cost)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001) : 
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                    feed_dict = {X: x_data, Y: y_data})
    if step >= 1995 :        
        print(step, cost_val, hy_val) 

1995 1.1806544 [[152.48491]
 [183.68408]
 [180.931  ]
 [196.48694]
 [140.41037]
 [102.21916]]
1996 1.180503 [[152.48473]
 [183.68419]
 [180.93094]
 [196.48682]
 [140.41054]
 [102.21929]]
1997 1.1803776 [[152.48453]
 [183.68425]
 [180.93086]
 [196.48672]
 [140.41069]
 [102.21942]]
1998 1.1802391 [[152.48436]
 [183.68436]
 [180.9308 ]
 [196.48665]
 [140.41086]
 [102.21956]]
1999 1.1800917 [[152.48418 ]
 [183.68448 ]
 [180.93074 ]
 [196.48657 ]
 [140.41103 ]
 [102.219696]]
2000 1.1799489 [[152.48401 ]
 [183.68457 ]
 [180.93068 ]
 [196.4865  ]
 [140.41121 ]
 [102.219826]]


In [40]:
### cf. ask one's score
#### Kim = [100, 70, 101]
#### Lee and Park = [[60, 70, 110], [90, 100, 80]]

print("Kim's Finall Score will be", sess.run(hypothesis, 
                                     feed_dict = {X: [[100, 70, 101]] })
     )

print("Lee & Park's Final Score will be", sess.run(hypothesis, 
                                          feed_dict = {X: [[60, 70, 110], [90, 100, 80]] })
     )

Kim's Finall Score will be [[180.87515]]
Lee & Park's Final Score will be [[150.37334]
 [183.4686 ]]
